language: rust
rust:
  - stable
  - beta
  - nightly
addons:
  # Force the latest firefox, otherwise we get an old ESR version
  # that we don't even support
  firefox: latest
  apt:
    packages:
    - firefox
    - xvfb
before_script:
  - bin/travis/before
script:
  - TC="${TRAVIS_RUST_VERSION}" bin/build_tc
